services:
  # main:
  #   build:
  #     context: .
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   environment:
  #     - OLLAMA_HOST=ollama
  #     - MODEL=mistral:latest
  #     - QUERY="Combien d'utilisateurs sont en france ?"
  #   stdin_open: true
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     ollama:
  #       condition: service_started

  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    env_file:
      - ./.env
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-local:/root/.ollama

  # adminer:
  #   image: adminer
  #   ports:
  #     - 8080:8080

volumes:
  db-data:
  ollama-local:
    external: true


